# Generated by Django 3.2.20 on 2023-07-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodblog', '0004_recipe_featured_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
